spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: 1q2w3e4rQ!!
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP ??? ? ?? (?? ? ??)
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    # ??? ?? ??/?? ??: none, validate, update, create, create-drop
    hibernate:
      ddl-auto: update

    # SQL ?? ??
    show-sql: true

    # Hibernate ???? ?? ??
    properties:
      hibernate:
        # ?? SQL ??? ? ??
        format_sql: true
        use_sql_comments: true
        generate_statistics: false

        # ?? ??
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

        # ?? ??(N+1) ??
        default_batch_fetch_size: 16

        # 2? ?? ?? (?? ? ???)
        cache:
          use_second_level_cache: true
          use_query_cache: false
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE